```{r}
library(tidyverse)
library(randomForest)
library(ggthemr)
```


```{r}
#Random Forest
data <- read.csv("G:\\GS\\Chapter3\\19-22_Soft.csv")  %>% 
  mutate(NDRE2 = as.numeric(NDRE2), NWI2 = as.numeric(NWI2)) %>% drop_na(c(BUAC,Can_Cover,NDVI,NDRE1,MTVI,NDRE2,NWI1,NWI2,NDRE2))
  
data <- dplyr::select(data,Name1,BUAC,Location,Year,Trial,NDVI,NDRE1,MTVI,NDRE2,NWI1,NWI2,NDRE2)
data$ENV <- paste(data$Location,"_",data$Year)

data$Name1 <- as.factor(data$Name1)
data$Year <- as.factor(data$Year)
data$Location <- as.factor(data$Location)
data$ENV <- as.factor(data$ENV)

### Set Training and Test Datasets 
dt = sort(sample(nrow(data), nrow(data)*.7))
train<-data[dt,]
test<-data[-dt,]
#train <- filter(data, Year != 2022)
#test <- filter(data, Year == 2022)

set.seed(3)
```


```{r}
### Find Ideal mtry ----------------------------------------------
mtry <- tuneRF(data[-c(1:3:5,12)],data$BUAC, ntreeTry=2000,
               stepFactor=1.5,improve=0.01, trace=TRUE, plot=TRUE)
best.m <- mtry[mtry[, 2] == min(mtry[, 2]), 1]
print(mtry)
print(best.m)
```


```{r}
### Build RF ----------------------------------------------
rf <- randomForest(formula = BUAC~NDVI+NDRE1+MTVI+NDRE2+NWI1+NWI2, 
             ntree= 2000,
             method="anova",
             importance=TRUE,
             data=data,
             mtry=6)


### Visualize variable importance ----------------------------------------------
```


```{r}
# Get variable importance from the model fit
ImpData <- as.data.frame(importance(rf))
ImpData$Var.Names <- row.names(ImpData)

ggthemr("fresh")
fig1 <- ggplot(ImpData, aes(x=Var.Names, y=`%IncMSE`)) +
  geom_segment( aes(x=Var.Names, xend=Var.Names, y=0, yend=`%IncMSE`)) +
  geom_point(aes(size = IncNodePurity/100000), alpha=1) +
  coord_flip() +
  theme(
    legend.position= c(0.2, 0.34),
    panel.grid.major.y = element_blank(),
    panel.border = element_blank(),
    axis.ticks.y = element_blank(),
    axis.text.y = element_text(angle = 0),
    axis.title = element_text( face = "bold"),
    legend.title = element_text(face = "bold")
  ) +
  ggtitle("SRI Importance in Grain Yield Variability") +
  labs(y = "% Decrease in MSE", x = "Variables", size = "Node Purity")

ggsave(filename = "RF_Acc.jpg", plot = fig1, device = "jpeg", height = 4, width = 5.5, units = "in")
fig1
```

```{r}
#Graph Index Importance
importance <- importance(rf)
varImportance <- data.frame(Variables = row.names(importance),
                            Importance = round(importance[,"%IncMSE"],2))

rankImportance = varImportance %>%
  mutate(Rank=paste('#',dense_rank(desc(Importance))))

ggthemr("light")

fig2 <- ggplot(rankImportance,aes(x=reorder(Variables,Importance),
 y=Importance,fill=Importance))+ 
 geom_bar(stat='identity') + 
 geom_text(aes(x = Variables, y = 0.5, label = Rank),
 hjust=0, vjust=0.55, size = 4, colour = 'white') +
 labs(x = 'Variables') +
 coord_flip()

ggsave(filename = "RF_Import.jpg", plot = fig2, device = "jpeg", height = 5, width = 6.5, units = "in")
fig2
```

```{r}
buac_pred <- predict(rf, newdata = test, allow.new.levels=TRUE)
buac_true <- test$BUAC
cor(buac_true,buac_pred)

```


